version: '3.8'

services:
  climate-analyzer:
    # restart: always
    build:
      context: .
    image: climate-analyzer:latest
    container_name: climate-changer-server
    ports:
      - 8000:8000  # Map port 8000 for potential external use
    volumes:
      - ./data:/app/data  # Map host 'data/' folder to container '/app/data'
      - ./logs:/app/logs  # Map host 'logs/' folder to container '/app/logs'
      - ./output:/app/output  # Map host 'output/' folder to container '/app/output'
    working_dir: /app  # Set the working directory inside the container
    command: ["Rscript", "data_visualization.R"]  # Automatically execute the new R script
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD", "Rscript", "--vanilla", "/app/data_visualization.R"]
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
