# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/compose/compose-file/

version: '3.8'

services:
  climate-analyzer:
    build:
      context: .
    image: climate-analyzer:latest
    container_name: climate-changer-server
    ports:
      - 8000:8000  # Map port 8000 for potential external use
    volumes:
      - ./data:/app/data  # Map host 'data/' folder to container '/app/data'
    working_dir: /app  # Set the working directory inside the container
    command: ["Rscript", "data_analysis.R"]  # Automatically execute the R script
    stdin_open: true
    tty: true

# The commented-out section below is an example of how to define a PostgreSQL
# database that your application can use. `depends_on` tells Docker Compose to
# start the database before your application. The `db-data` volume persists the
# database data between container restarts. The `db-password` secret is used
# to set the database password. You must create `db/password.txt` and add
# a password of your choosing to it before running `docker compose up`.
# Uncomment and modify if you want to add a database service.

#   db:
#     image: postgres
#     restart: always
#     user: postgres
#     secrets:
#       - db-password
#     volumes:
#       - db-data:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_DB=example
#       - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
#     expose:
#       - 5432
#     healthcheck:
#       test: ["CMD", "pg_isready"]
#       interval: 10s
#       timeout: 5s
#       retries: 5

volumes:
  db-data:

# Uncomment this section if you decide to use the database service above
# secrets:
#   db-password:
#     file: db/password.txt
